### ISSUE TITLE
"gop" command not working on windows

### ISSUE THREAD

**Issue by SpyrexDE** [felix-hellman/gop#3]
I followed the installation instructions, but after trying to run "gop" in any command line on Windows 10, the command can't be found.

**Comment by felix-hellman** [comment]
I found several issues with the installer and it was only working for me because of some faulty assumptions.
Please add a comment here if you are still having issues. (The new version should be 0.0.2 instead of 0.0.1)

**Comment by felix-hellman** [comment]
When installing via git after this I had an issue where the python package would not be installed on path
If it's not on your path you can (using git-bash)

```bash
find ~/ -name 'gop.exe'
```
and add Python to your path.

e.g.

```bash
cd to/path/where/python/has/installed/gop
PATH="`pwd`:$PATH"
```

**Comment by felix-hellman** [comment]
I added some general instructions in the readme as well.
